### ISSUE TITLE
Access Token instead of Username/Password

### ISSUE THREAD

**Issue by nvdokh** [meg768/homebridge-my-tesla#14]
Can you please add the feature, so we don’t have to save our Tesla account username/password in the config.json? Homebridge-Tesla already has access token feature working.

**Comment by meg768** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/4264015/147292817-1f00b2ad-63ec-49a0-b27b-40b1672cf6ca.png">

Username and password is no longer supported. You now have to supply a refresh token.
