### ISSUE TITLE
Can't log in without TESLA_USER and TESLA_PASSWORD environment set

### ISSUE THREAD

**Issue by sandeen** [meg768/homebridge-my-tesla#9]
Hi, I'm running the latest, on node 12, and unless I set the above environment vars, I end up with

```
[12/7/2019, 17:39:22] [Tesla] Initializing Tesla platform...
[12/7/2019, 17:39:22] [Tesla] Environment variables PUSHOVER_USER and/or PUSHOVER_TOKEN not defined. Push notifications will not be able to be sent.
[12/7/2019, 17:39:22] Error: Need Tesla credentials. A username must be specified
    at new TeslaAPI (/opt/node/lib/node_modules/homebridge-my-tesla/src/tesla-api.js:25:19)
    at new Vehicle (/opt/node/lib/node_modules/homebridge-my-tesla/src/vehicle.js:20:9)
    at /opt/node/lib/node_modules/homebridge-my-tesla/src/platform.js:34:27
    at Array.forEach (<anonymous>)
    at Platform.accessories (/opt/node/lib/node_modules/homebridge-my-tesla/src/platform.js:33:30)
    at Server._loadPlatformAccessories (/opt/node/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/opt/node/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/opt/node/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/opt/node/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```
I tried to debug the js to see what's going on but failed.  Any suggestions?

**Comment by meg768** [comment]
Are you missing to specify Tesla login credentials in ~/.homebridge/config.json?

**Comment by sandeen** [comment]
No, I have username and password specified.  This seems to happen before the config file gets parsed?

**Comment by meg768** [comment]
{
            "platform": "Tesla",
            "name": "Tesla",
            "debug": true,
            "vehicles": [
                {
                    "name": "Model 3",
                    "vin": "my-vin",
                    "username": "my-username",
                    "password": "my-password",
                    "accessories": {
                        "ping": {
                            "name": "Ping",
                            "requiredBatteryLevel": 40,
                            "timerInterval": 5,
                            "enabled": true
                        },
                        "charging": {
                            "name": "Laddning",
                            "enabled": true
                        },
                        "hvac": {
                            "name": "Fläkten",
                            "requiredBatteryLevel": 20,
                            "enabled": true
                        },
                        "doors": {
                            "name": "Dörren",
                            "enabled": true
                        },
                        "outsideTemperature": {
                            "name": "Ute",
                            "enabled": true
                        },
                        "insideTemperature": {
                            "name": "Inne",
                            "enabled": true
                        },
                        "thermostat": {
                            "name": "Termostat",
                            "requiredBatteryLevel": 40,
                            "timerInterval": 2,
                            "enabled": true
                        }
                    }
                }
            ]
        }

**Comment by sandeen** [comment]
If I set the environment variables so that I can get further, and do some logging in vehicle.js around

```
    login() {
        var configLoginOptions = {username:this.config.username, password:this.config.password, clientID:this.config.clientID, clientSecret:this.config.clientSecret};
        var processLoginOptions = {username:process.env.TESLA_USER, password:process.env.TESLA_PASSWORD, clientID:process.env.TESLA_CLIENT_ID, clientSecret:process.env.TESLA_CLIENT_SECRET};
        var loginOptions = {...configLoginOptions, ...processLoginOptions};

        return super.login(loginOptions);
    }
```

I see that configLoginOptions is set at this point with the proper username and password.  (I also see it in processLoginOptions)

But without the env vars, I don't get to login()

**Comment by meg768** [comment]
This is my setup in config.json. Replace the "my-xxx" with your VIN and credentials. Any luck?

**Comment by meg768** [comment]
Try skipping the environment variables and just specify them in config.json.

**Comment by sandeen** [comment]
Is it required that accessories be specified?  I only have this and no accessories explicitly listed:
```
	        "vehicles": [
		        {         
		            "name": "Model 3",       
		            "vin": "5YJ3E1EBXJFXXXX",
                            "username": "XXX",
                            "password": "XXX"
		        }
		 ]
```

**Comment by sandeen** [comment]
If I skip the env vars, I get the original error I opened this issue with.

**Comment by meg768** [comment]
You should not have to specify **accessories** under **vehicles**. Your config looks fine. Let me test the same config...

**Comment by meg768** [comment]
Well, something is obviously wrong here. Give me a moment to fix it.

**Comment by meg768** [comment]
Modified my config.json to the following and it works fine. Just published version 1.0.28 to both GitHub and npm to make sure the latest code is out there.

```json
        {
            "platform": "Tesla",
            "name": "Tesla",
            "debug": true,
            "vehicles": [
                {
                    "name": "Model 3",
                    "vin": "5YJ3E7EB9KF240654",
                    "username": "xxx",
                    "password": "xxx"
                }
            ]
        }
```

**Comment by sandeen** [comment]
Hm, I had 1.0.27 already ... I'll update & retry just to see ...

**Comment by meg768** [comment]
Keep me posted. I want this fixed.

**Comment by sandeen** [comment]
Same issue (and stripped my config.json down to only the tesla platform)
I'm happy to sprinkle console.log()'s around in the code and report results if that helps?  Turning debug on didn't give me any more info prior to the error.

**Comment by sandeen** [comment]
Just FWIW, I'm running this on raspbian stretch on a pi-zero-2, and had to get an unofficial node 12 build - but I'd be surprised if that matters...

**Comment by meg768** [comment]
Should not matter. You still get the "Need Tesla credentials" error?!

**Comment by sandeen** [comment]
I do. :)

**Comment by sandeen** [comment]
I'll sprinkle around some logging and see if that provides you with any info...

**Comment by meg768** [comment]
Please do...

**Comment by sandeen** [comment]
Does this help?  Seems like  the constructor that is throwing the error doesn't yet have the username/password parsed into the config options?  (This run was with the env vars set as well as the json configuration, so I could get a bit further through the code)
```
[12/7/2019, 22:56:53] Loading 1 platforms...
[12/7/2019, 22:56:53] [Tesla] Initializing Tesla platform...
[12/7/2019, 22:56:53] [Tesla] Environment variables PUSHOVER_USER and/or PUSHOVER_TOKEN not defined. Push notifications will not be able to be sent.
[12/7/2019, 22:56:53] [Tesla] Creating accessories...
tesla-api.js TeslaAPI constructor options.username undefined process.env.TESLA_USER XX@XX
vehicle.js Vehicle constructor, config.username = XX@XX
```
(you are certain that you don't have the env vars set?) :)

**Comment by meg768** [comment]
Looking in to the loading of **.env** right now. It should be loading **~/.homebridge/.env** but it loads from the current directory (!). Try removing any **.env** files then the properties from the config file will be used.

**Comment by sandeen** [comment]
I don't see any .env files under ~/.homebridge
I can instrument that loading if you show me where it is...
Not sure if this suppresses .env loading, but if I comment out
`// require('dotenv').config();`
I have the same problem FWIW.

**Comment by meg768** [comment]
I removed the loading of **.env**. Now I get the same error message you. Hang on...

**Comment by meg768** [comment]
OK, try it now. Just published 1.0.33. Disabled all **.env** loading.

**Comment by sandeen** [comment]
Seems like that works now; unset the env vars and it loads up properly from the config file.

**Comment by sandeen** [comment]
Hm, maybe this is what fixed it?

```
diff --git a/src/vehicle.js b/src/vehicle.js
index 97752b1..79c2b9e 100755
--- a/src/vehicle.js
+++ b/src/vehicle.js
@@ -16,8 +16,7 @@ module.exports = class Vehicle extends TeslaAPI  {
 
     constructor(platform, config) {
 
-
-        super({log:platform.log, debug:platform.debug, vin:config.vin});
+        super({log:platform.log, debug:platform.debug, vin:config.vin, username:config.username, password:config.password});
 
         this.pushover = platform.pushover;
         this.config = config;
```

**Comment by meg768** [comment]
Yes, as you said, the constructor needed username and password from the config file... :) 

Will publish a more stable version tomorrow, probably skipping the **.env** loading, I don't think it's really needed...

**Comment by sandeen** [comment]
Ok I did a quick bisect and it is f4084c91 that fixed it, presumably 
```
diff --git a/src/vehicle.js b/src/vehicle.js
index 4fac2cc..2809259 100755
--- a/src/vehicle.js
+++ b/src/vehicle.js
@@ -17,7 +17,7 @@ module.exports = class Vehicle extends TeslaAPI  {
     constructor(platform, config) {
 
 
-        super({log:platform.log, debug:platform.debug, vin:config.vin});
+        super({log:platform.log, debug:platform.debug, vin:config.vin, username:config.username, password:config.password});
 
         this.pushover = platform.pushover;
         this.config = config;
```

**Comment by meg768** [comment]
https://github.com/meg768/homebridge-my-tesla/releases/tag/1.0.35
